export const scenesConfig = [
  { scene: 'exemplo-a', position: 1 },
  { scene: 'exemplo-b', position: 2 },
  { scene: 'exemplo-c', position: 3 },
  { scene: 'exemplo-b', position: 4 },
  { scene: 'exemplo-c', position: 4 },
  { scene: 'backoffice', position: 5 },
  { scene: 'supervisor', position: 6 },
  { scene: 'backoffice', position: 7 },
  { scene: 'supervisor', position: 7 },
  // Tutorial do Supervisor — roteiro atualizado em 8 cenas.
  { scene: 'supervisor-cena-1-tela', position: 8 },
  { scene: 'supervisor-cena-2-normal-para-media', position: 9 },
  { scene: 'supervisor-cena-2-media-sobe', position: 10 },
  { scene: 'supervisor-cena-3-media-para-alta', position: 11 },
  { scene: 'supervisor-cena-4-aviso-alta', position: 12 },
  { scene: 'supervisor-cena-5-demanda-critica', position: 13 },
  { scene: 'supervisor-cena-6-demanda-critica-sobe', position: 14 },
  { scene: 'supervisor-cena-7-aviso-estourado', position: 15 },
];
